install-scripts$(EXEEXT):
	mkdir -p /etc/default/fazia
	cp scripts/fzdaq.default /etc/default/fazia/fzdaq
	cp scripts/fzdaq /etc/init.d
	cp scripts/fzcontroller.default /etc/default/fazia/fzcontroller
	cp scripts/fzcontroller /etc/init.d
	cp src/main/log4cpp.properties /etc/default/fazia
	mkdir -p /opt/FzDAQ/config
	cp config/* /opt/FzDAQ/config
