#!/bin/sh

# JMS2RDB start-stop-daemon 
set -e

export PATH="$PATH:/opt/FzDAQ:/usr/sbin:/sbin"

SCREEN_OPTS=" -d -m -S jms2rdb /opt/JMS2RDB/JMS2RDB -pluginCustomization /opt/JMS2RDB/plugin_customization.ini"

case "$1" in
  start)
        echo -n "Starting JMS2RDB: "
        if pgrep -a java  | grep JMS2RDB > /dev/null; then
           echo -n "JMS2RDB instance already exists !"
        else 
           cd /opt/JMS2RDB
           /usr/bin/screen $SCREEN_OPTS
           echo -n "JMS2RDB instance created"
        fi
        echo "."
	;;
  stop)
        echo -n "Stopping JMS2RDB: "
        /usr/bin/screen -r jms2rdb -X quit
        echo "."
	;;
  status)
        echo -n "JMS2RDB instances: "
        /usr/bin/screen -list
        echo "."
        ;;
  *)
	echo "Usage: "$1" {start|stop|status}"
	exit 1
esac

exit 0
